"""Reads the mod's action surface out of its Java sources.

The mod lives in its own repository, so CI cannot look at it. What CI can check
is a fixture: this writes down, per action, the parameters the mod actually
reads, and `tests/test_minecraft_contract.py` holds the brain's tool schemas
against it. Re-run this whenever a skill on the mod side gains or loses a
parameter, and review the diff — a parameter the brain sends and the mod never
reads is silently ignored, which is the failure this exists to catch.

    uv run python tools/mc_contract.py --mod ../beacraft
"""

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set

# `case "move_to":` ... up to the next case or the end of the switch
CASE = re.compile(r'case\s+"([a-z_]+)"\s*:(.*?)(?=case\s+"|default\s*:)', re.S)
# the skill the case hands the work to
SKILL = re.compile(r"new\s+([A-Za-z]+Skill)\s*\(")
# what the mod reads out of the json it was sent
READS = re.compile(r'params\.(?:has|get)\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*\)')
# what ActionManager fills in itself before the skill ever sees it
INJECTS = re.compile(r'params\.addProperty\(\s*"([A-Za-z_][A-Za-z0-9_]*)"')
KNOWN = re.compile(r"KNOWN_ACTIONS\s*=.*?List\.of\((.*?)\)\)\)", re.S)
# the actions that run beside the current one instead of stopping it
CONCURRENT = re.compile(r"CONCURRENT_ACTIONS\s*=.*?List\.of\((.*?)\)\)\)", re.S)


def extract(mod_root: Path) -> Dict[str, object]:
    base = mod_root / "src/main/java/com/example/beacraft"
    manager = (base / "ActionManager.java").read_text(encoding="utf-8")

    known = sorted(re.findall(r'"([a-z_]+)"', KNOWN.search(manager).group(1)))
    concurrent_match = CONCURRENT.search(manager)
    concurrent = sorted(re.findall(r'"([a-z_]+)"', concurrent_match.group(1))) if concurrent_match else []
    stray = [a for a in concurrent if a not in known]
    if stray:
        sys.exit(f"concurrent but not in KNOWN_ACTIONS: {stray}")

    actions: Dict[str, Dict[str, object]] = {}
    for case in CASE.finditer(manager.split("switch (action)", 1)[1]):
        name, body = case.group(1), case.group(2)
        skill_match = SKILL.search(body)
        skill = skill_match.group(1) if skill_match else None
        injected: Set[str] = set(INJECTS.findall(body))

        reads: Set[str] = set()
        if skill:
            source = base / "skills" / f"{skill}.java"
            if not source.exists():
                sys.exit(f"{name}: {skill}.java not found under {source.parent}")
            reads = set(READS.findall(source.read_text(encoding="utf-8")))

        actions[name] = {
            "skill": skill,
            # what the model is allowed to set: everything the skill reads that
            # ActionManager does not fill in on its own
            "accepts": sorted(reads - injected),
            "injected_by_mod": sorted(injected),
        }

    missing: List[str] = [a for a in known if a not in actions]
    if missing:
        sys.exit(f"declared in KNOWN_ACTIONS but not wired in the switch: {missing}")

    return {
        "_comment": "Generated by tools/mc_contract.py — do not edit by hand.",
        "known_actions": known,
        "concurrent_actions": concurrent,
        "actions": dict(sorted(actions.items())),
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--mod", required=True, type=Path, help="path to the beacraft checkout")
    ap.add_argument("--out", type=Path,
                    default=Path(__file__).resolve().parent.parent / "tests/fixtures/minecraft_contract.json")
    args = ap.parse_args()

    contract = extract(args.mod.expanduser().resolve())
    args.out.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8")
    print(f"{args.out}: {len(contract['actions'])} actions")


if __name__ == "__main__":
    main()
